# Miktos Workflows Release
name: Release

# GitHub Actions workflow for creating releases
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release Archive
      run: |
        zip -r miktos-workflows-${{ github.ref_name }}.zip workflows/ README.md LICENSE
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Miktos Workflows ${{ github.ref_name }}
        body: |
          ## What's Changed
          
          This release includes the latest workflow templates and improvements.
          
          ### Installation
          
          1. Download the `miktos-workflows-${{ github.ref_name }}.zip` file
          2. Extract to your ComfyUI custom_nodes directory
          3. Follow the individual workflow README instructions
          
          ### Workflows Included
          
          See the [README](https://github.com/LegnaPetiteTour/miktos-workflows/blob/main/README.md) for a complete list of available workflows.
        files: |
          miktos-workflows-${{ github.ref_name }}.zip
        draft: false
        prerelease: false
